// File generated from our OpenAPI spec by Stainless.

package com.hello_world_testingggg.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hello_world_testingggg.api.core.JsonValue
import com.hello_world_testingggg.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AddressTest {

    @Test
    fun create() {
        val address =
            Address.builder()
                .city("Palo Alto")
                .geo(Address.GeoPoint.builder().latitude(37.4443).longitude(-122.1598).build())
                .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                .relatedMoney(
                    Money.builder()
                        .amount(2500L)
                        .currency("USD")
                        .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                        .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                        .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                        .relatedPet(
                            Pet.builder()
                                .name("doggie")
                                .addPhotoUrl("string")
                                .id(10L)
                                .acquisitionChannel(Pet.AcquisitionChannel.BREEDER)
                                .category(JsonValue.from(mapOf<String, Any>()))
                                .microchipId("string")
                                .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                                .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                                .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                                .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                                .relatedUser(JsonValue.from(mapOf<String, Any>()))
                                .status(PetStatus.AVAILABLE)
                                .addTag(JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                        .relatedTag(JsonValue.from(mapOf<String, Any>()))
                        .relatedUser(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                .relatedPet(
                    Pet.builder()
                        .name("doggie")
                        .addPhotoUrl("string")
                        .id(10L)
                        .acquisitionChannel(Pet.AcquisitionChannel.BREEDER)
                        .category(JsonValue.from(mapOf<String, Any>()))
                        .microchipId("string")
                        .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                        .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                        .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                        .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                        .relatedUser(JsonValue.from(mapOf<String, Any>()))
                        .status(PetStatus.AVAILABLE)
                        .addTag(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                .relatedTag(JsonValue.from(mapOf<String, Any>()))
                .relatedUser(JsonValue.from(mapOf<String, Any>()))
                .state("CA")
                .street("437 Lytton")
                .zip("94301")
                .build()

        assertThat(address.city()).isEqualTo("Palo Alto")
        assertThat(address.geo())
            .isEqualTo(Address.GeoPoint.builder().latitude(37.4443).longitude(-122.1598).build())
        assertThat(address._relatedCategory()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(address._relatedCustomer()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(address.relatedMoney())
            .isEqualTo(
                Money.builder()
                    .amount(2500L)
                    .currency("USD")
                    .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                    .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                    .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                    .relatedPet(
                        Pet.builder()
                            .name("doggie")
                            .addPhotoUrl("string")
                            .id(10L)
                            .acquisitionChannel(Pet.AcquisitionChannel.BREEDER)
                            .category(JsonValue.from(mapOf<String, Any>()))
                            .microchipId("string")
                            .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                            .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                            .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                            .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                            .relatedUser(JsonValue.from(mapOf<String, Any>()))
                            .status(PetStatus.AVAILABLE)
                            .addTag(JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                    .relatedTag(JsonValue.from(mapOf<String, Any>()))
                    .relatedUser(JsonValue.from(mapOf<String, Any>()))
                    .build()
            )
        assertThat(address._relatedOrder()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(address.relatedPet())
            .isEqualTo(
                Pet.builder()
                    .name("doggie")
                    .addPhotoUrl("string")
                    .id(10L)
                    .acquisitionChannel(Pet.AcquisitionChannel.BREEDER)
                    .category(JsonValue.from(mapOf<String, Any>()))
                    .microchipId("string")
                    .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                    .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                    .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                    .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                    .relatedUser(JsonValue.from(mapOf<String, Any>()))
                    .status(PetStatus.AVAILABLE)
                    .addTag(JsonValue.from(mapOf<String, Any>()))
                    .build()
            )
        assertThat(address._relatedShelter()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(address._relatedTag()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(address._relatedUser()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(address.state()).isEqualTo("CA")
        assertThat(address.street()).isEqualTo("437 Lytton")
        assertThat(address.zip()).isEqualTo("94301")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val address =
            Address.builder()
                .city("Palo Alto")
                .geo(Address.GeoPoint.builder().latitude(37.4443).longitude(-122.1598).build())
                .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                .relatedMoney(
                    Money.builder()
                        .amount(2500L)
                        .currency("USD")
                        .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                        .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                        .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                        .relatedPet(
                            Pet.builder()
                                .name("doggie")
                                .addPhotoUrl("string")
                                .id(10L)
                                .acquisitionChannel(Pet.AcquisitionChannel.BREEDER)
                                .category(JsonValue.from(mapOf<String, Any>()))
                                .microchipId("string")
                                .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                                .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                                .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                                .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                                .relatedUser(JsonValue.from(mapOf<String, Any>()))
                                .status(PetStatus.AVAILABLE)
                                .addTag(JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                        .relatedTag(JsonValue.from(mapOf<String, Any>()))
                        .relatedUser(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                .relatedPet(
                    Pet.builder()
                        .name("doggie")
                        .addPhotoUrl("string")
                        .id(10L)
                        .acquisitionChannel(Pet.AcquisitionChannel.BREEDER)
                        .category(JsonValue.from(mapOf<String, Any>()))
                        .microchipId("string")
                        .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                        .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                        .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                        .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                        .relatedUser(JsonValue.from(mapOf<String, Any>()))
                        .status(PetStatus.AVAILABLE)
                        .addTag(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                .relatedTag(JsonValue.from(mapOf<String, Any>()))
                .relatedUser(JsonValue.from(mapOf<String, Any>()))
                .state("CA")
                .street("437 Lytton")
                .zip("94301")
                .build()

        val roundtrippedAddress =
            jsonMapper.readValue(jsonMapper.writeValueAsString(address), jacksonTypeRef<Address>())

        assertThat(roundtrippedAddress).isEqualTo(address)
    }
}
