// File generated from our OpenAPI spec by Stainless.

package com.hello_world_testingggg.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hello_world_testingggg.api.core.JsonValue
import com.hello_world_testingggg.api.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class MoneyTest {

    @Test
    fun create() {
        val money =
            Money.builder()
                .amount(2500L)
                .currency("USD")
                .relatedAddress(
                    Address.builder()
                        .city("Palo Alto")
                        .geo(
                            Address.GeoPoint.builder()
                                .latitude(37.4443)
                                .longitude(-122.1598)
                                .build()
                        )
                        .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                        .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                        .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                        .relatedPet(
                            Pet.builder()
                                .name("doggie")
                                .addPhotoUrl("string")
                                .id(10L)
                                .acquisitionChannel(Pet.AcquisitionChannel.BREEDER)
                                .category(JsonValue.from(mapOf<String, Any>()))
                                .microchipId("string")
                                .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                                .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                                .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                                .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                                .relatedUser(JsonValue.from(mapOf<String, Any>()))
                                .status(PetStatus.AVAILABLE)
                                .addTag(JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                        .relatedTag(JsonValue.from(mapOf<String, Any>()))
                        .relatedUser(JsonValue.from(mapOf<String, Any>()))
                        .state("CA")
                        .street("437 Lytton")
                        .zip("94301")
                        .build()
                )
                .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                .relatedPet(
                    Pet.builder()
                        .name("doggie")
                        .addPhotoUrl("string")
                        .id(10L)
                        .acquisitionChannel(Pet.AcquisitionChannel.BREEDER)
                        .category(JsonValue.from(mapOf<String, Any>()))
                        .microchipId("string")
                        .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                        .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                        .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                        .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                        .relatedUser(JsonValue.from(mapOf<String, Any>()))
                        .status(PetStatus.AVAILABLE)
                        .addTag(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                .relatedTag(JsonValue.from(mapOf<String, Any>()))
                .relatedUser(JsonValue.from(mapOf<String, Any>()))
                .build()

        assertThat(money.amount()).isEqualTo(2500L)
        assertThat(money.currency()).isEqualTo("USD")
        assertThat(money.relatedAddress())
            .isEqualTo(
                Address.builder()
                    .city("Palo Alto")
                    .geo(Address.GeoPoint.builder().latitude(37.4443).longitude(-122.1598).build())
                    .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                    .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                    .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                    .relatedPet(
                        Pet.builder()
                            .name("doggie")
                            .addPhotoUrl("string")
                            .id(10L)
                            .acquisitionChannel(Pet.AcquisitionChannel.BREEDER)
                            .category(JsonValue.from(mapOf<String, Any>()))
                            .microchipId("string")
                            .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                            .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                            .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                            .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                            .relatedUser(JsonValue.from(mapOf<String, Any>()))
                            .status(PetStatus.AVAILABLE)
                            .addTag(JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                    .relatedTag(JsonValue.from(mapOf<String, Any>()))
                    .relatedUser(JsonValue.from(mapOf<String, Any>()))
                    .state("CA")
                    .street("437 Lytton")
                    .zip("94301")
                    .build()
            )
        assertThat(money._relatedCategory()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(money._relatedCustomer()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(money._relatedOrder()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(money.relatedPet())
            .isEqualTo(
                Pet.builder()
                    .name("doggie")
                    .addPhotoUrl("string")
                    .id(10L)
                    .acquisitionChannel(Pet.AcquisitionChannel.BREEDER)
                    .category(JsonValue.from(mapOf<String, Any>()))
                    .microchipId("string")
                    .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                    .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                    .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                    .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                    .relatedUser(JsonValue.from(mapOf<String, Any>()))
                    .status(PetStatus.AVAILABLE)
                    .addTag(JsonValue.from(mapOf<String, Any>()))
                    .build()
            )
        assertThat(money._relatedShelter()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(money._relatedTag()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(money._relatedUser()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val money =
            Money.builder()
                .amount(2500L)
                .currency("USD")
                .relatedAddress(
                    Address.builder()
                        .city("Palo Alto")
                        .geo(
                            Address.GeoPoint.builder()
                                .latitude(37.4443)
                                .longitude(-122.1598)
                                .build()
                        )
                        .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                        .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                        .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                        .relatedPet(
                            Pet.builder()
                                .name("doggie")
                                .addPhotoUrl("string")
                                .id(10L)
                                .acquisitionChannel(Pet.AcquisitionChannel.BREEDER)
                                .category(JsonValue.from(mapOf<String, Any>()))
                                .microchipId("string")
                                .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                                .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                                .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                                .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                                .relatedUser(JsonValue.from(mapOf<String, Any>()))
                                .status(PetStatus.AVAILABLE)
                                .addTag(JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                        .relatedTag(JsonValue.from(mapOf<String, Any>()))
                        .relatedUser(JsonValue.from(mapOf<String, Any>()))
                        .state("CA")
                        .street("437 Lytton")
                        .zip("94301")
                        .build()
                )
                .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                .relatedPet(
                    Pet.builder()
                        .name("doggie")
                        .addPhotoUrl("string")
                        .id(10L)
                        .acquisitionChannel(Pet.AcquisitionChannel.BREEDER)
                        .category(JsonValue.from(mapOf<String, Any>()))
                        .microchipId("string")
                        .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                        .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                        .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                        .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                        .relatedUser(JsonValue.from(mapOf<String, Any>()))
                        .status(PetStatus.AVAILABLE)
                        .addTag(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                .relatedTag(JsonValue.from(mapOf<String, Any>()))
                .relatedUser(JsonValue.from(mapOf<String, Any>()))
                .build()

        val roundtrippedMoney =
            jsonMapper.readValue(jsonMapper.writeValueAsString(money), jacksonTypeRef<Money>())

        assertThat(roundtrippedMoney).isEqualTo(money)
    }
}
