// File generated from our OpenAPI spec by Stainless.

package com.hello_world_testingggg.api.models.pet

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.hello_world_testingggg.api.core.JsonValue
import com.hello_world_testingggg.api.core.jsonMapper
import com.hello_world_testingggg.api.models.Address
import com.hello_world_testingggg.api.models.Money
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PetRetrievePremiumResponseTest {

    @Test
    fun create() {
        val petRetrievePremiumResponse =
            PetRetrievePremiumResponse.builder()
                .name("doggie")
                .addPhotoUrl("string")
                .id(10L)
                .acquisitionChannel(Pet.AcquisitionChannel.BREEDER)
                .category(JsonValue.from(mapOf<String, Any>()))
                .microchipId("string")
                .relatedAddress(
                    Address.builder()
                        .city("Palo Alto")
                        .geo(Address.Geo.builder().latitude(37.4443).longitude(-122.1598).build())
                        .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                        .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                        .relatedMoney(
                            Money.builder()
                                .amount(2500L)
                                .currency("USD")
                                .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                                .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                                .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                                .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                                .relatedTag(JsonValue.from(mapOf<String, Any>()))
                                .relatedUser(JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                        .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                        .relatedTag(JsonValue.from(mapOf<String, Any>()))
                        .relatedUser(JsonValue.from(mapOf<String, Any>()))
                        .state("CA")
                        .street("437 Lytton")
                        .zip("94301")
                        .build()
                )
                .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                .relatedMoney(
                    Money.builder()
                        .amount(2500L)
                        .currency("USD")
                        .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                        .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                        .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                        .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                        .relatedTag(JsonValue.from(mapOf<String, Any>()))
                        .relatedUser(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                .relatedUser(JsonValue.from(mapOf<String, Any>()))
                .status(PetStatus.AVAILABLE)
                .addTag(JsonValue.from(mapOf<String, Any>()))
                .premiumSince(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .coverageLimit(0L)
                .insurance(
                    PetRetrievePremiumResponse.Insurance.builder()
                        .planId("planId")
                        .provider("provider")
                        .deductible(0L)
                        .premium(
                            Money.builder()
                                .amount(2500L)
                                .currency("USD")
                                .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                                .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                                .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                                .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                                .relatedTag(JsonValue.from(mapOf<String, Any>()))
                                .relatedUser(JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .tier(PetRetrievePremiumResponse.Insurance.Tier.BASIC)
                        .build()
                )
                .pedigree(
                    PetRetrievePremiumResponse.Pedigree.builder()
                        .certified(true)
                        .addLineage("string")
                        .registry("registry")
                        .build()
                )
                .build()

        assertThat(petRetrievePremiumResponse.name()).isEqualTo("doggie")
        assertThat(petRetrievePremiumResponse.photoUrls()).containsExactly("string")
        assertThat(petRetrievePremiumResponse.id()).isEqualTo(10L)
        assertThat(petRetrievePremiumResponse.acquisitionChannel())
            .isEqualTo(Pet.AcquisitionChannel.BREEDER)
        assertThat(petRetrievePremiumResponse._category())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(petRetrievePremiumResponse.microchipId())
            .isEqualTo(Pet.MicrochipId.ofString("string"))
        assertThat(petRetrievePremiumResponse.relatedAddress())
            .isEqualTo(
                Address.builder()
                    .city("Palo Alto")
                    .geo(Address.Geo.builder().latitude(37.4443).longitude(-122.1598).build())
                    .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                    .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                    .relatedMoney(
                        Money.builder()
                            .amount(2500L)
                            .currency("USD")
                            .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                            .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                            .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                            .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                            .relatedTag(JsonValue.from(mapOf<String, Any>()))
                            .relatedUser(JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                    .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                    .relatedTag(JsonValue.from(mapOf<String, Any>()))
                    .relatedUser(JsonValue.from(mapOf<String, Any>()))
                    .state("CA")
                    .street("437 Lytton")
                    .zip("94301")
                    .build()
            )
        assertThat(petRetrievePremiumResponse._relatedCategory())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(petRetrievePremiumResponse._relatedCustomer())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(petRetrievePremiumResponse.relatedMoney())
            .isEqualTo(
                Money.builder()
                    .amount(2500L)
                    .currency("USD")
                    .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                    .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                    .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                    .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                    .relatedTag(JsonValue.from(mapOf<String, Any>()))
                    .relatedUser(JsonValue.from(mapOf<String, Any>()))
                    .build()
            )
        assertThat(petRetrievePremiumResponse._relatedOrder())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(petRetrievePremiumResponse._relatedShelter())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(petRetrievePremiumResponse._relatedUser())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(petRetrievePremiumResponse.status()).isEqualTo(PetStatus.AVAILABLE)
        assertThat(petRetrievePremiumResponse.tags())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(petRetrievePremiumResponse.premiumSince())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(petRetrievePremiumResponse.coverageLimit())
            .isEqualTo(PetRetrievePremiumResponse.CoverageLimit.ofLong(0L))
        assertThat(petRetrievePremiumResponse.insurance())
            .isEqualTo(
                PetRetrievePremiumResponse.Insurance.builder()
                    .planId("planId")
                    .provider("provider")
                    .deductible(0L)
                    .premium(
                        Money.builder()
                            .amount(2500L)
                            .currency("USD")
                            .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                            .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                            .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                            .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                            .relatedTag(JsonValue.from(mapOf<String, Any>()))
                            .relatedUser(JsonValue.from(mapOf<String, Any>()))
                            .build()
                    )
                    .tier(PetRetrievePremiumResponse.Insurance.Tier.BASIC)
                    .build()
            )
        assertThat(petRetrievePremiumResponse.pedigree())
            .isEqualTo(
                PetRetrievePremiumResponse.Pedigree.builder()
                    .certified(true)
                    .addLineage("string")
                    .registry("registry")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val petRetrievePremiumResponse =
            PetRetrievePremiumResponse.builder()
                .name("doggie")
                .addPhotoUrl("string")
                .id(10L)
                .acquisitionChannel(Pet.AcquisitionChannel.BREEDER)
                .category(JsonValue.from(mapOf<String, Any>()))
                .microchipId("string")
                .relatedAddress(
                    Address.builder()
                        .city("Palo Alto")
                        .geo(Address.Geo.builder().latitude(37.4443).longitude(-122.1598).build())
                        .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                        .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                        .relatedMoney(
                            Money.builder()
                                .amount(2500L)
                                .currency("USD")
                                .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                                .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                                .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                                .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                                .relatedTag(JsonValue.from(mapOf<String, Any>()))
                                .relatedUser(JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                        .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                        .relatedTag(JsonValue.from(mapOf<String, Any>()))
                        .relatedUser(JsonValue.from(mapOf<String, Any>()))
                        .state("CA")
                        .street("437 Lytton")
                        .zip("94301")
                        .build()
                )
                .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                .relatedMoney(
                    Money.builder()
                        .amount(2500L)
                        .currency("USD")
                        .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                        .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                        .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                        .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                        .relatedTag(JsonValue.from(mapOf<String, Any>()))
                        .relatedUser(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                .relatedUser(JsonValue.from(mapOf<String, Any>()))
                .status(PetStatus.AVAILABLE)
                .addTag(JsonValue.from(mapOf<String, Any>()))
                .premiumSince(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .coverageLimit(0L)
                .insurance(
                    PetRetrievePremiumResponse.Insurance.builder()
                        .planId("planId")
                        .provider("provider")
                        .deductible(0L)
                        .premium(
                            Money.builder()
                                .amount(2500L)
                                .currency("USD")
                                .relatedCategory(JsonValue.from(mapOf<String, Any>()))
                                .relatedCustomer(JsonValue.from(mapOf<String, Any>()))
                                .relatedOrder(JsonValue.from(mapOf<String, Any>()))
                                .relatedShelter(JsonValue.from(mapOf<String, Any>()))
                                .relatedTag(JsonValue.from(mapOf<String, Any>()))
                                .relatedUser(JsonValue.from(mapOf<String, Any>()))
                                .build()
                        )
                        .tier(PetRetrievePremiumResponse.Insurance.Tier.BASIC)
                        .build()
                )
                .pedigree(
                    PetRetrievePremiumResponse.Pedigree.builder()
                        .certified(true)
                        .addLineage("string")
                        .registry("registry")
                        .build()
                )
                .build()

        val roundtrippedPetRetrievePremiumResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(petRetrievePremiumResponse),
                jacksonTypeRef<PetRetrievePremiumResponse>(),
            )

        assertThat(roundtrippedPetRetrievePremiumResponse).isEqualTo(petRetrievePremiumResponse)
    }
}
